### ISSUE TITLE
Blast from the past

### ISSUE THREAD

**Issue by stuartpb** [opws/opws-news#1]
I *knew* the lineage of this dataset dated back to before blot.pw, but I couldn't remember where I'd worked on it. Here's a file I just found in my old TouchSmart's "Projects" folder called "listings.yaml", in a directory called "gatekeeper", with a Creation time of ‎Thursday, ‎July ‎26, ‎2012, ‏‎12:23:26 AM and a Last Modified time of Thursday, ‎July ‎26, ‎2012, ‏‎3:46:51 PM:

```yaml
- site: FreeDNS (afraid.org)
  home: https://freedns.afraid.org
  changepw: https://freedns.afraid.org/profile/password.php
  forgot: https://freedns.afraid.org/password/
  maxchars: 16
  treat: dns
  tests:
    tls: optional
    cookie: session

- site: Yahoo!
  home: http://www.yahoo.com
  changepw: https://edit.yahoo.com/config/change_pw
  forgot: https://edit.yahoo.com/forgotroot
  treat: provider
  tests:
    tls: Yahoo's main page does not allow connecting via HTTPS. Other pages upgrade to HTTPS.
    cookie: blobs
  notes: Yahoo's "Forgot Password" page also allows you to report a compromised account.

- site: Dreamhost
  home: http://dreamhost.com
  changepw: https://panel.dreamhost.com/index.cgi?tree=billing.secure&
  tests:
    sessionttl: 3 months and counting
  incidents:
  - date: Jan 20 2012
```
